-- =============================================================================
-- V1__init.sql - RSR initial schema
--
-- DO NOT EDIT THIS FILE once it has run against any database. Flyway stores a
-- checksum per migration; changing an applied file makes every later startup
-- fail with "Migration checksum mismatch". Corrections go into V2__*.sql.
--
-- Conventions used throughout:
--   * UUID primary keys, generated by the database. gen_random_uuid() is built
--     into PostgreSQL 13+, so no pgcrypto extension is required.
--   * Enum-like columns are VARCHAR + CHECK, not native PostgreSQL ENUM types.
--     Adding a value later is a one-line ALTER; renaming or removing one from a
--     native ENUM is not, and JPA maps plain strings without extra plumbing.
--   * TIMESTAMPTZ everywhere. TIMESTAMP without a time zone silently reads back
--     as a different instant once the server and the phone disagree about UTC.
-- =============================================================================


-- =============================================================================
-- users
-- =============================================================================
CREATE TABLE users (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    is_blocked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_users_role CHECK (role IN ('USER', 'MODERATOR', 'ADMIN'))
);

-- Case-insensitive uniqueness. A plain UNIQUE on the column would happily
-- accept both 'User@x.ge' and 'user@x.ge' as two separate accounts.
CREATE UNIQUE INDEX ux_users_email_lower ON users (LOWER(email));

-- is_blocked exists from day one because the app stores user-generated content:
-- App Store and Google Play both require a way to block an abusive user.


-- =============================================================================
-- questions - the atomic unit of content. A question exists on its own and may
-- belong to zero, one, or many packages.
-- =============================================================================
CREATE TABLE questions (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id         UUID        NOT NULL,

    text              TEXT        NOT NULL,
    answer            TEXT        NOT NULL,
    comment           TEXT,
    source            TEXT,

    -- "razdatka": material handed to the team before the question is read.
    handout_text      TEXT,
    handout_media_url TEXT,

    visibility        VARCHAR(20) NOT NULL DEFAULT 'PRIVATE',
    status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_questions_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT ck_questions_visibility CHECK (visibility IN ('PRIVATE', 'PUBLIC')),
    CONSTRAINT ck_questions_status     CHECK (status IN
        ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'ARCHIVED'))
);

-- ON DELETE RESTRICT, deliberately: author credit is the only incentive to
-- publish into the public catalogue, so an author row may not vanish from under
-- published questions. Removing a person means anonymising the users row rather
-- than deleting it.

CREATE INDEX ix_questions_author  ON questions (author_id);

-- The public catalogue always filters on exactly this pair.
CREATE INDEX ix_questions_catalog ON questions (status, visibility, created_at DESC);

-- Word search over question text. 'simple' is the right configuration here:
-- PostgreSQL ships no Georgian dictionary, so there is no stemming to apply and
-- a language-specific config would only mangle the tokens. Drop this index if
-- catalogue search turns out to need trigram matching instead.
CREATE INDEX ix_questions_text_fts ON questions
    USING GIN (to_tsvector('simple', text));


-- =============================================================================
-- question_answers - additional accepted wordings of the same answer.
-- =============================================================================
CREATE TABLE question_answers (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id   UUID NOT NULL,
    accepted_text TEXT NOT NULL,

    CONSTRAINT fk_question_answers_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX ix_question_answers_question ON question_answers (question_id);


-- =============================================================================
-- question_parts - sub-questions of a DUPLET (2 parts) or BLITZ (3 parts).
-- Absent for an ordinary single question.
-- =============================================================================
CREATE TABLE question_parts (
    id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id UUID    NOT NULL,
    position    INTEGER NOT NULL,
    text        TEXT    NOT NULL,
    answer      TEXT    NOT NULL,

    CONSTRAINT fk_question_parts_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE,
    CONSTRAINT uq_question_parts_position UNIQUE (question_id, position),
    CONSTRAINT ck_question_parts_position CHECK (position > 0)
);


-- =============================================================================
-- packages - a thematic view over questions. Owns its own visibility and
-- status; it does not own the questions themselves.
-- =============================================================================
CREATE TABLE packages (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id   UUID         NOT NULL,

    title       VARCHAR(200) NOT NULL,
    theme       VARCHAR(200),
    description TEXT,

    visibility  VARCHAR(20)  NOT NULL DEFAULT 'PRIVATE',
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',

    -- Set only for UNLISTED packages: the link you send to friends.
    share_code  VARCHAR(32),

    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_packages_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE RESTRICT,

    CONSTRAINT uq_packages_share_code UNIQUE (share_code),
    CONSTRAINT ck_packages_visibility CHECK (visibility IN
        ('PRIVATE', 'UNLISTED', 'PUBLIC')),
    CONSTRAINT ck_packages_status     CHECK (status IN
        ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', 'ARCHIVED'))
);

-- UNIQUE permits many NULLs in PostgreSQL, so every private package can leave
-- share_code empty without colliding.

CREATE INDEX ix_packages_author  ON packages (author_id);
CREATE INDEX ix_packages_catalog ON packages (status, visibility, created_at DESC);


-- =============================================================================
-- package_questions - the link table. tour_number groups questions into rounds.
-- =============================================================================
CREATE TABLE package_questions (
    package_id  UUID    NOT NULL,
    question_id UUID    NOT NULL,
    position    INTEGER NOT NULL,
    tour_number INTEGER,

    CONSTRAINT pk_package_questions PRIMARY KEY (package_id, question_id),

    CONSTRAINT fk_package_questions_package FOREIGN KEY (package_id)
        REFERENCES packages (id) ON DELETE CASCADE,

    -- RESTRICT, not CASCADE: a question that someone else already put in a
    -- package must not be deletable out from under them. The supported way to
    -- retire a question is status = 'ARCHIVED', which keeps existing packages
    -- playable while hiding it from the catalogue and from new packages.
    CONSTRAINT fk_package_questions_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE RESTRICT,

    CONSTRAINT uq_package_questions_position UNIQUE (package_id, position),
    CONSTRAINT ck_package_questions_position CHECK (position > 0)
);

CREATE INDEX ix_package_questions_question ON package_questions (question_id);


-- =============================================================================
-- teams / team_members - stage 2 (realtime multiplayer). Created empty now so
-- that game_sessions.team_id can be a real foreign key from the start; adding
-- it later would mean migrating a table that already holds live sessions.
-- =============================================================================
CREATE TABLE teams (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name       VARCHAR(100) NOT NULL,
    owner_id   UUID         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_teams_owner FOREIGN KEY (owner_id)
        REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE team_members (
    team_id   UUID        NOT NULL,
    user_id   UUID        NOT NULL,
    role      VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pk_team_members PRIMARY KEY (team_id, user_id),
    CONSTRAINT fk_team_members_team FOREIGN KEY (team_id)
        REFERENCES teams (id) ON DELETE CASCADE,
    CONSTRAINT fk_team_members_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_team_members_role CHECK (role IN ('CAPTAIN', 'MEMBER'))
);


-- =============================================================================
-- game_sessions - one playthrough of a package.
-- =============================================================================
CREATE TABLE game_sessions (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID        NOT NULL,
    package_id  UUID        NOT NULL,

    -- NULL for a solo game. Populated in stage 2.
    team_id     UUID,

    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_game_sessions_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_sessions_package FOREIGN KEY (package_id)
        REFERENCES packages (id) ON DELETE RESTRICT,
    CONSTRAINT fk_game_sessions_team FOREIGN KEY (team_id)
        REFERENCES teams (id) ON DELETE SET NULL,

    CONSTRAINT ck_game_sessions_finished CHECK
        (finished_at IS NULL OR finished_at >= started_at)
);

CREATE INDEX ix_game_sessions_user    ON game_sessions (user_id, started_at DESC);
CREATE INDEX ix_game_sessions_package ON game_sessions (package_id);


-- =============================================================================
-- session_answers - one row per question played, with a snapshot of the
-- question as it read at that moment.
-- =============================================================================
CREATE TABLE session_answers (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id  UUID        NOT NULL,

    -- Nullable on purpose, see the ON DELETE SET NULL below.
    question_id UUID,

    -- The snapshot is what makes past results trustworthy: editing or deleting
    -- a question later must never rewrite a game that has already been played.
    question_text_snapshot TEXT NOT NULL,
    answer_snapshot        TEXT NOT NULL,

    user_answer TEXT,

    -- NULL until the player self-assesses. Automatic fuzzy matching is not
    -- reliable for this game, so the player marks their own answer.
    is_correct  BOOLEAN,

    answered_at TIMESTAMPTZ,

    CONSTRAINT fk_session_answers_session FOREIGN KEY (session_id)
        REFERENCES game_sessions (id) ON DELETE CASCADE,

    -- SET NULL rather than RESTRICT: the snapshot columns already hold
    -- everything needed to display the result, so a deleted question leaves the
    -- history intact and merely loses its link back to the catalogue.
    CONSTRAINT fk_session_answers_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE SET NULL,

    CONSTRAINT uq_session_answers UNIQUE (session_id, question_id)
);

CREATE INDEX ix_session_answers_session ON session_answers (session_id);


-- =============================================================================
-- reports - in-app abuse reporting. Required by both app stores for
-- user-generated content.
-- =============================================================================
CREATE TABLE reports (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- SET NULL keeps the report actionable after the reporter deletes their
    -- account.
    reporter_id UUID,
    question_id UUID        NOT NULL,

    reason      VARCHAR(30) NOT NULL,
    details     TEXT,
    status      VARCHAR(20) NOT NULL DEFAULT 'OPEN',

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,

    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id)
        REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT fk_reports_question FOREIGN KEY (question_id)
        REFERENCES questions (id) ON DELETE CASCADE,

    CONSTRAINT ck_reports_reason CHECK (reason IN
        ('INCORRECT_ANSWER', 'DUPLICATE', 'OFFENSIVE', 'COPYRIGHT', 'SPAM', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (status IN
        ('OPEN', 'RESOLVED', 'DISMISSED'))
);

-- The moderator queue reads exactly this.
CREATE INDEX ix_reports_status ON reports (status, created_at);
